apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller-app
  template:
    metadata:
      name: caller-app
      labels:
        app: caller-app
        version: v1
    spec:
      containers:
      - name: caller-app
        image: svbugakov/kuber:istio_caller
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: VERSION
            value: "v1"
---
apiVersion: v1
kind: Service
metadata:
  name: caller-service
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      name: http
  selector:
    app: caller-app